### ISSUE TITLE
Can't install unlisted scripts

### ISSUE THREAD

**Issue by Maymne** [scriptish/scriptish.github.com#18]
Noticed an unlisted script (http://userscripts.org/scripts/show/115081) and decided to try it out. When clicking on the link to install, it takes me to an error page which says:
403 Forbidden - Hotlinking of unlisted scripts is forbidden - http://userscripts.org/about/unlisted

I'm logged in to userscripts.org, but it appears that the way that Scriptish installs uses hotlinking in a non-functional way. I'd prefer not to need to enable GM just to install unlisted scripts which I may or may not actually keep... enjoying the speed boost from the efficiency.

**Comment by erikvold** [comment]
I will archive the repo soon.
